# Subimos el archivo csv


>Nota técnica
>El archivo está en latín no en UTF y en cp1252
```{python}
import os
import pandas as pd

df = pd.read_csv('ant-exceso-velocidad-febrero-2022.csv', 
        sep=';',
        encoding='latin-1')
print("Cargado con cp1252")
print(df.head())
```


## Librerias 

```{python}

!pip install vl-convert-python>=1.6.0 vegafusion[embed]>=1.5.0

import altair as alt

```

## Gráfico de barras entre ciudad y velocidad

>Nota técnica
>Me dio un error de máximo de utilización por eso uso 

```{python}
alt.data_transformers.enable("vegafusion")
```

```{python}
# Configurar para datasets grandes sin vegafusion
alt.data_transformers.enable('default', max_rows=20000)

# Tu gráfico funcionará ahora
alt.Chart(df).mark_bar().encode(
    x=alt.X('CIUDAD_EXCESO:N', title='Ciudad'),
    y=alt.Y('mean(VELOCIDAD):Q', title='Velocidad Promedio'),
    color=alt.Color('CIUDAD_EXCESO:N', legend=None)
).properties(
    width=600,
    height=400,
    title='Velocidad Promedio por Ciudad'
).interactive()
```

### Analisis 
El data set al ser sobre las multas de infracciones se ve que todas las ciudades tiene una gráfica sobre los 90 kilómetros, que ya marca la contravención y podemos ver las ciudades como el tambo que sobrepasa los 120


### Diagrama de dispersión temporal

Primero convertimos la fecha a datetime


La data de velocidad no tiene información fácil de tabular para un gráfico de dispersión, por lo que la grafica solo cumple con el conocimiento de elaboración de la misma

```{python}

df['FECHA_ALERTA'] = pd.to_datetime(df['FECHA_ALERTA'], format='%d/%m/%Y')

alt.Chart(df).mark_circle(size=120).encode(
    x=alt.X('FECHA_ALERTA:T', title='Fecha de Alerta'),
    y=alt.Y('VELOCIDAD:Q', title='Velocidad (km/h)'),
    color=alt.Color('IDENTIFICACION_OPERADORA:N', title='Operadora'),
    tooltip=['IDENTIFICACION_OPERADORA', 'VELOCIDAD', 'FECHA_ALERTA', 'HORA_ALERTA', 'CIUDAD_OPERADORA']
).properties(
    title='Velocidades de Exceso por Fecha y Operadora',
    width=600,
    height=400
).interactive()
```

### Analisis 
No concluyente





>Pie pagina
>Tipos de datos en Altair:
>:T = Temporal (fechas y horas)
>:Q = Quantitative (números continuos)
>:O = Ordinal (categorías con orden)
>:N = Nominal (categorías sin orden)
